default_platform(:android)

platform :android do

  desc "Upload internal test release to Google Play"
  lane :deploy_internal do
    upload_to_play_store(
        package_name: 'de.zieglr.mysafe',
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true
    )
  end

end
